# Generated by Django 4.0.6 on 2024-08-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tour_form.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='tour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='tour_form.tourtype', verbose_name='Тип тура'),
        ),
    ]
