# Generated by Django 4.0.6 on 2024-08-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_branch_alter_user_region'),
        ('tour_form', '0003_tourform_tourpeople_touroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourform',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_forms', to='users.region', verbose_name='Регион'),
        ),
    ]
