# Generated by Django 4.0.6 on 2024-08-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0005_tourform_room_count_alter_touroffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroffer',
            name='tour_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_offer', to='tour_form.tourform', verbose_name='Заявка на тур'),
        ),
    ]
