# Generated by Django 4.0.6 on 2024-08-08 08:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0006_alter_touroffer_tour_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroffer',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
