# Generated by Django 4.2 on 2024-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour_form", "0010_alter_touroffer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourform",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
