# Generated by Django 4.2 on 2024-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0011_alter_tourform_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Davlat va shahar', 'verbose_name_plural': 'Davlatlar va shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='tourform',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='touroffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma taklif', 'verbose_name_plural': "Buyurtma qo'shish"},
        ),
        migrations.AddField(
            model_name='tourform',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='tourform',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Куплено'),
        ),
    ]
