# Generated by Django 4.2 on 2024-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0012_alter_country_options_alter_tourform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroffer',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
