# Generated by Django 4.2 on 2024-08-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_branch_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_form', '0013_touroffer_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touroffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agentlik taklifi', 'verbose_name_plural': 'Agentlik takliflari'},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'ordering': ['order'], 'verbose_name': 'Sayohat turi', 'verbose_name_plural': 'Sayohat turlari'},
        ),
        migrations.AlterField(
            model_name='tourform',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='users.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='tour_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.tourtype', verbose_name='Тип тура'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
