# Generated by Django 4.2 on 2024-08-19 05:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_branch_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_form', '0014_alter_touroffer_options_alter_tourtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Shahar', 'verbose_name_plural': 'Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='tourpeople',
            options={'verbose_name': 'Buyurtmadagi shaxs', 'verbose_name_plural': 'Buyurtmadagi shaxslar'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tour_form.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='country',
            name='tour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='tour_form.tourtype', verbose_name='Sayohat turi'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.city', verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='from_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='holidays',
            field=models.PositiveIntegerField(verbose_name='Dam olish kunlari soni'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Sotib olingan'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='users.region', verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xonalar soni'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='to_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='tour_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='tour_form.tourtype', verbose_name='Sayohat turi'),
        ),
        migrations.AlterField(
            model_name='tourform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Javob berilgan'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shtrixkod'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='tour_offers', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('thinking', 'Thinking'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='tour_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_offer', to='tour_form.tourform', verbose_name='Tur buyurtmasi'),
        ),
        migrations.AlterField(
            model_name='tourpeople',
            name='birth_date',
            field=models.DateField(verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='tourpeople',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='tourpeople',
            name='gender',
            field=models.CharField(max_length=15, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='tourpeople',
            name='tour_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_people', to='tour_form.tourform', verbose_name='Tur buyurtmasi'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
    ]
