# Generated by Django 4.2 on 2024-08-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_branch_coefficient_alter_branch_name_and_more'),
        ('tour_form', '0015_alter_city_options_alter_tourpeople_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourform',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_forms', to='users.branch', verbose_name='Filial'),
        ),
    ]
