# Generated by Django 4.2 on 2024-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0016_tourform_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourform',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz'),
        ),
    ]
