# Generated by Django 4.2 on 2024-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0017_alter_tourform_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroffer',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hisoblangan narx'),
        ),
        migrations.AddField(
            model_name='touroffer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Haqiqiy narx'),
        ),
    ]
