# Generated by Django 4.2 on 2024-08-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0019_alter_touroffer_calculated_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroffer',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Turpaket'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Sotuv narxi'),
        ),
        migrations.AlterField(
            model_name='touroffer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Kirim narxi'),
        ),
    ]
