# Generated by Django 4.2 on 2024-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_form', '0021_alter_tourform_is_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroffer',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('offered', 'Taklif etilgan'), ('thinking', "Maslahatlashib ko'raman"), ('accepted', 'Buyurtma beraman'), ('rejected', 'Qiziqdim, lekin boshqa safar')], default='offered', max_length=255, verbose_name='Status'),
        ),
    ]
