# Generated by Django 4.0.6 on 2024-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0002_userbooking_userbookingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
