# Generated by Django 4.0.6 on 2024-08-08 08:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0003_userbooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
