# Generated by Django 4.2 on 2024-08-12 04:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0005_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='tour_images', verbose_name='Изображение'),
        ),
    ]
