# Generated by Django 4.2 on 2024-08-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_branch_alter_user_region'),
        ('tour_catalog', '0006_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.region', verbose_name='Регион'),
        ),
    ]
