# Generated by Django 4.2 on 2024-08-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0007_userbooking_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tur paket', 'verbose_name_plural': 'Tur paketlar'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ['order'], 'verbose_name': 'Turpaket kategoriya', 'verbose_name_plural': 'Turpaket kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='userbooking',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
