# Generated by Django 4.2 on 2024-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0008_alter_tour_options_alter_tourcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
