# Generated by Django 4.2 on 2024-08-19 05:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_branch_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_catalog', '0009_tour_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourprice',
            options={'ordering': ['people_count'], 'verbose_name': 'Tur uchun narx', 'verbose_name_plural': 'Tur uchun narxlar'},
        ),
        migrations.AlterModelOptions(
            name='userbookingprice',
            options={'verbose_name': 'Buyurtmadagi tur narxi', 'verbose_name_plural': 'Buyurtmadagi tur narxlari'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shtrixkod'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tour_catalog.tourcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='days_count',
            field=models.PositiveIntegerField(verbose_name='Kunlar soni'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='tour_images', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tur nomi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='people_count',
            field=models.PositiveIntegerField(verbose_name='Odamlar soni'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='tourprice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tourprice',
            name='people_count',
            field=models.PositiveIntegerField(verbose_name='Odamlar soni'),
        ),
        migrations.AlterField(
            model_name='tourprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='tourprice',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tour_catalog.tour', verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.region', verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='tg_username',
            field=models.CharField(max_length=255, verbose_name='Telegramdagi username'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour_catalog.tour', verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userbookingprice',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='userbookingprice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='userbookingprice',
            name='tour_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='tour_catalog.tourprice', verbose_name='Tur uchun narx'),
        ),
        migrations.AlterField(
            model_name='userbookingprice',
            name='user_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_prices', to='tour_catalog.userbooking', verbose_name='Buyurtma'),
        ),
    ]
