# Generated by Django 4.2 on 2024-08-19 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_branch_coefficient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_catalog', '0010_alter_tourprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.region', verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
    ]
