# Generated by Django 4.2 on 2024-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0011_alter_userbooking_region_alter_userbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Sotildi'),
        ),
    ]
