# Generated by Django 4.2 on 2024-08-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_branch_coefficient_alter_branch_name_and_more'),
        ('tour_catalog', '0012_userbooking_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.branch', verbose_name='Filial'),
        ),
    ]
