# Generated by Django 4.2 on 2024-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0013_userbooking_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourprice',
            options={'ordering': ['order'], 'verbose_name': 'Tur uchun narx', 'verbose_name_plural': 'Tur uchun narxlar'},
        ),
        migrations.AddField(
            model_name='tourprice',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Mijoz'),
        ),
    ]
