# Generated by Django 4.2 on 2024-08-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0016_alter_userbooking_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Kirim narxi'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Sotuv narxi'),
        ),
    ]
