# Generated by Django 4.2 on 2024-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_catalog', '0017_alter_userbooking_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingprice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotuv narxi'),
        ),
    ]
