# Generated by Django 4.2 on 2024-08-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_branch_alter_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.region', verbose_name='Регион'),
        ),
    ]
