# Generated by Django 4.2 on 2024-08-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_branch_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Sotuvchilar'},
        ),
    ]
