# Generated by Django 4.2 on 2024-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_branch_coefficient_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('client', 'Sotuvchi')], default='client', max_length=10, verbose_name='Foydalanuvchi turi'),
        ),
    ]
