# Generated by Django 4.2 on 2024-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('client', 'Sotuvchi'), ('supervisor', 'Supervizor')], default='client', max_length=10, verbose_name='Foydalanuvchi turi'),
        ),
    ]
